name: Build and test CLI

on:
  push:
    branches: [ "main" ]

jobs:
  build-macos-arm:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Konan cache
        id: konan-cache
        uses: actions/cache@v4
        with:
          path: ~/.konan/dependencies
          key: ${{ runner.os }}-konan-2.1.20
      - name: Build and test
        run: ./gradlew :cli:macosArm64Binaries :core:macosArm64Test :cli:macosArm64Test

  build-macos-intel:
    runs-on: macos-13
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Konan cache
        id: konan-cache
        uses: actions/cache@v4
        with:
          path: ~/.konan/dependencies
          key: ${{ runner.os }}-konan-2.1.20
      - name: Build and test
        run: ./gradlew :cli:macosX64Binaries :core:macosX64Test :cli:macosX64Test

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Install CURL dev headers
        run: sudo apt-get install libcurl4-gnutls-dev
      - name: Konan cache
        id: konan-cache
        uses: actions/cache@v4
        with:
          path: ~/.konan/dependencies
          key: ${{ runner.os }}-konan-2.1.20
      - name: Build and test
        run: ./gradlew :cli:linuxX64Binaries :cli:assembleJvmDist :cli:linuxX64Test :core:linuxX64Test :gradle-plugin:test

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Konan cache
        id: konan-cache
        uses: actions/cache@v4
        with:
          path: ~/.konan/dependencies
          key: ${{ runner.os }}-konan-2.1.20
      - name: Build and test
        run: ./gradlew :cli:mingwX64Binaries :cli:mingwX64Test :core:mingwX64Test