name: Build binaries

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: read
  pull-requests: read
  statuses: write

jobs:
  build:
    runs-on: macos-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/buildBinaries')
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v3
        id: comment-branch
      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build binaries and packages
        run: ./gradlew :cli:assembleAll :cli:buildAllDebs --stacktrace --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_isSnapshot: true
      - name: Upload artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-release-artifacts
          path: |
            cli/build/bin/zip/*.zip
            cli/build/distributions/*.zip
            cli/build/distributions/*.deb
      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@v2.0.1
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
      - name: Update summary
        run: |
          echo "[Binaries](${{ steps.upload_artifact.outputs.artifact-url }})" >> $GITHUB_STEP_SUMMARY

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.project.kotlin.incremental.multiplatform=false -Dorg.gradle.project.kotlin.native.disableCompilerDaemon=true -Dorg.gradle.jvmargs="-Xmx12g -Dfile.encoding=UTF-8"