name: Build and test CLI

on:
  push:
    branches: [ "main" ]

jobs:
  build-macos-arm:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew :cli:macosArm64Binaries
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-update-checker-macos-arm
          path: cli/build/bin/macosArm64/releaseExecutable/dependency-update-checker.kexe

  build-macos-intel:
    runs-on: macos-13
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew :cli:macosX64Binaries
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-update-checker-macos-intel
          path: cli/build/bin/macosX64/releaseExecutable/dependency-update-checker.kexe

  build-other:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Install CURL dev headers
        run: sudo apt-get install libcurl4-gnutls-dev
      - name: Build
        run: ./gradlew :cli:mingwX64Binaries :cli:linuxX64Binaries :cli:jvmDistZip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-update-checker-other
          path: |
            cli/build/bin/mingxX64/releaseExecutable/dependency-update-checker.exe
            cli/build/bin/linuxX64/releaseExecutable/dependency-update-checker.kexe
            distributions/dependency-update-checker-jvm.zip