name: check

on: workflow_dispatch
#  push:
#    branches: [ "main" ]
#  pull_request:
#      branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, macos-13, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Install CURL dev headers
        run: sudo apt-get install libcurl4-gnutls-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Konan cache
        id: konan-cache
        uses: actions/cache@v4
        with:
          path: ~/.konan/dependencies
          key: ${{ runner.os }}-${{ runner.arch }}-konan-2.1.20
      - name: Check
        run: ./gradlew check
      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: check-results-${{ matrix.os }}
          path: |
            */build/test-results/**/TEST-*.xml
            */build/reports/detekt/*.sarif

  merge-reports:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: check-results
          delete-merged: true