name: check

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#    paths-ignore:
#      - '*.md'
#      - '*/*.md'
#  pull_request:
#    branches: [ "main" ]
#    paths-ignore:
#      - '*.md'
#      - '*/*.md'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
            - os: macos-latest
              TEST_TASK: macosArm64Test
            - os: windows-latest
              TEST_TASK: mingwX64Test
            - os: ubuntu-latest
              TEST_TASK: linuxX64Test jvmTest test detektAll
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Check
        run: ./gradlew ${{matrix.TEST_TASK}} --stacktrace
      - name: Test publication
        run: ./gradlew publishToMavenLocal --stacktrace
        if: matrix.os == 'ubuntu-latest'
      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: check-results-${{ matrix.os }}
          path: '*/build/test-results/**/TEST-*.xml'
      - name: Copy SARIF files to global result directory
        run: mkdir -p build/reports/detekt && cp */build/reports/detekt/*.sarif build/reports/detekt/
      - name: Publish Detekt reports
        if: matrix.os == 'ubuntu-latest'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'build/reports/detekt'

  merge-reports:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: check-results
          delete-merged: true

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.project.kotlin.incremental.multiplatform=false -Dorg.gradle.project.kotlin.native.disableCompilerDaemon=true -Dorg.gradle.jvmargs="-Xmx12g -Dfile.encoding=UTF-8"